### ISSUE TITLE
Largest area rectangular sub-matrix with equal number of 1’s and 0’s

### ISSUE THREAD

**Issue by matthewsamuel95** [matthewsamuel95/ACM-ICPC-Algorithms#91]
## Given a binary matrix. The problem is to find the largest area rectangular sub-matrix with equal number of 1’s and 0’s.

Input : mat[][] = { {0, 0, 1, 1},
                    {0, 1, 1, 0},
                    {1, 1, 1, 0},
                    {1, 0, 0, 1} }
Output : 8 sq. units
(Top, left): (0, 0)
(Bottom, right): (3, 1)

Input : mat[][] = { {0, 0, 1, 1},
                    {0, 1, 1, 1} }            
Output : 6 sq. units

Time Complexity : O(Row x Col)

**Comment by supriyanta** [comment]
Could you please explain further?

**Comment by pBuddhi** [comment]
i will do it.

**Comment by matthewsamuel95** [comment]
Yes Any language. https://www.youtube.com/watch?v=g8bSdXCG-lA This resource should be useful that the algorithm is possible to run in O(Row x Col).

**Comment by anushree816** [comment]
Thanks for the link.. It was helpful.

On 26 Oct 2017 9:57 p.m., "matthewsamuel95" <notifications@github.com>
wrote:

Reopened #91
<https://github.com/matthewsamuel95/ACM-ICPC-Algorithms/issues/91>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/matthewsamuel95/ACM-ICPC-Algorithms/issues/91#event-1312346255>,
or mute the thread
